name: 'Terraform Plan and Apply'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: hashicorp/setup-terraform@v1

    - name: Init
      run: terraform init

    - name: Create Plan
      run: terraform plan -out=terraform.plan

    - name: Upload Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform.plan
        path: terraform.plan

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: hashicorp/setup-terraform@v1

    - name: Init
      run: terraform init
    
    - name: Download Plan
      uses: actions/download-artifact@v3
      with:
        name: terraform.plan
        path: .

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Apply Plan
      run: terraform apply -auto-approve terraform.plan